# -*- coding: utf-8 -*-
"""Cópia de Exercicio_LISTAS_07_08_24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_iuJZE_rdaO4qon1CdpHK96Mu_2sFS2

# **Exercícios utilizando Listas Python**

## 1. Soma dos Elementos da Lista
Dada uma lista de números, calcule a soma de todos os elementos.
"""

# Seu código aqui...
lista = [1, 2, 3, 4, 5]
soma= sum(lista)
print(f"A soma é:{soma}")

"Sum" é utilizado para somar os numeros

"""## 2. Produto dos elementos da lista
Dada uma lista de números, calcule o produto de todos os elementos.
"""

# Seu código aqui...
lista2 = [1, 2, 3, 4, 5]
produto = 1
for numero in lista2:
    produto *= numero
print(f"O produto de todos os elementos é: {produto}")

"""## 3. Encontre o menor elemento
Dada uma lista de números, encontre o menor elemento.
"""

# Seu código aqui...
lista3 = [1, 2, 3, 4, 5]
min(lista3)

"""## 4. Encontre o maior elemento
Dada uma lista de números, encontre o maior elemento.
"""

# Seu código aqui...
lista4 = [1, 2, 3, 4, 5]
max(lista4)

"""## 5. Contar Ocorrências de um Elemento
Dada uma lista de números e um número alvo, conte quantas vezes o alvo aparece na lista.
"""

# Seu código aqui...
lista5 = [1, 2, 3, 4, 3, 2, 1]

"""## 6. Remover duplicatas
Dada uma lista de números, crie uma nova lista sem elementos duplicados.
"""

# Seu código aqui...
lista6 = [1, 2, 2, 3, 4, 4, 5]
lista7=[1,2,3,4,5]

lista7 = list(set(lista6))

print(f"A nova lista sem duplicatas é: {lista7}")



"""## 7. Inverter uma lista
Dada uma lista de números, inverta a ordem dos elementos.
"""

# Seu código aqui...
lista6 = [1, 2, 3, 4, 5]

lista6.reverse()
print(f"A lista invertida é: {lista6}")

"""## 8. Intercalar Duas Listas
Dadas duas listas de números, crie uma nova lista intercalando os elementos das duas listas.
"""

# Seu código aqui...
lista81 = [1, 3, 5]
lista82 = [2, 4, 6]

"""## 9. Somar Elementos Correspondentes de Duas Listas
Dadas duas listas de números de mesmo tamanho, crie uma nova lista com a soma dos elementos correspondentes.
"""

# Seu código aqui...
lista91 = [1, 2, 3]
lista92 = [4, 5, 6]

"""## 10. Mover Zeros para o Fim
Dada uma lista de números, mova todos os zeros para o final da lista.
"""

# Seu código aqui...
lista10 = [0, 1, 0, 3, 12]